// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYYLQP-9oejV_nJz7T-nMNMkIWcHLJWTw',
    appId: '1:102405208547:web:9d450ab0fae9cbfb8848d6',
    messagingSenderId: '102405208547',
    projectId: 'sweetclick-59a74',
    authDomain: 'sweetclick-59a74.firebaseapp.com',
    storageBucket: 'sweetclick-59a74.firebasestorage.app',
    measurementId: 'G-0F6TL4ZYST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSVdQ6NaefzU4GP6xt1Imf4HXuMLqp3ZQ',
    appId: '1:102405208547:android:82d55dfbd750b8d58848d6',
    messagingSenderId: '102405208547',
    projectId: 'sweetclick-59a74',
    storageBucket: 'sweetclick-59a74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClf0P-Z_Lhv4ozfl9C1LTCWI7sJjDgqsU',
    appId: '1:102405208547:ios:a33ce87c6955e13e8848d6',
    messagingSenderId: '102405208547',
    projectId: 'sweetclick-59a74',
    storageBucket: 'sweetclick-59a74.firebasestorage.app',
    iosBundleId: 'com.example.sweetclick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClf0P-Z_Lhv4ozfl9C1LTCWI7sJjDgqsU',
    appId: '1:102405208547:ios:a33ce87c6955e13e8848d6',
    messagingSenderId: '102405208547',
    projectId: 'sweetclick-59a74',
    storageBucket: 'sweetclick-59a74.firebasestorage.app',
    iosBundleId: 'com.example.sweetclick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYYLQP-9oejV_nJz7T-nMNMkIWcHLJWTw',
    appId: '1:102405208547:web:b1bcb8ac118377068848d6',
    messagingSenderId: '102405208547',
    projectId: 'sweetclick-59a74',
    authDomain: 'sweetclick-59a74.firebaseapp.com',
    storageBucket: 'sweetclick-59a74.firebasestorage.app',
    measurementId: 'G-5Y8VW9SC5B',
  );
}
